### ISSUE TITLE
Local View Support

### ISSUE THREAD

**Issue by patmo141** [CGCookie/script-bakery#35]
If object is in local view, the new retopo mesh doesn't show up until user toggles local view.

**Comment by carter2422** [comment]
For local view, are we able to add the newly created geometry into the current local view? Rather than leaving and then re-entering? 

The current setup causes the view to change soon as you hit enter to confirm the mesh generation. This can be a bit disorientating as it takes you away from the area you were working on.

**Comment by patmo141** [comment]
not that I know of.  It seems that the object.local_view_layers is read only?  I'm sure we can "record" the current view matrix and then reset it...not pretty, but it may work.  New issue

**Comment by carter2422** [comment]
Cool sounds good. It should be possible. When working in Local View you're
able to add new objects to that local view with no shift in view.

Jonathan Williamson
http://cgcookie.com
