### ISSUE TITLE
Make Cyclic should be optional

### ISSUE THREAD

**Issue by carter2422** [CGCookie/script-bakery#66]
When working on torus objects and other ring-like forms, _Contours_ will automatically make the generated mesh cyclic once strokes are near enough to each other.

This functionality should be optional.

There should be a modal switch to toggle Cyclic on or off, making it a definitive choice rather than an _automatically_ detected one. If cyclic is on, it should only become cyclic once three or more strokes are created.

This should also be tied into the Toolbar option for **Make Cyclic**, allowing the user to define a default state.

**Comment by patmo141** [comment]
May I see a screen shot?  Are you telling me it automatically closes a torus in the "follow" direction not just in the cross section?

**Comment by carter2422** [comment]
Here you go. 

No cyclic:
http://cl.ly/QUPi

Cyclic detected:
http://cl.ly/QV1i

Cyclic cleaned up:
http://cl.ly/QVKC

**Comment by patmo141** [comment]
Ha ha, that's so awesome.  Totally accidental but really really cool.  I hadn't really thought about torus type objects and scenarios.  My "connectivity" algorithm works subtractively.  Eg, all combinations of pairs are considered valid until proven otherwise.  And connecting the tip to tail of a torus is a valid pair so it doesn't get removed.

**Comment by carter2422** [comment]
Hah that's awesome. I figured it was intentional. There's really not too many use cases for cyclic, but is something that will be nice to have when it's occasionally needed.

**Comment by patmo141** [comment]
it will become a problem if we have a hammerhead shaped pot/cup/mug handles or something.  It may try to hook back up to the beginning when it's not truly a closed object.  This is circumvent-able by confirming the geometry early and starting again.  For this reason, I'm going to keep this lower priority than other items for the immediate future and because it's not immediately apparent to me how to fix it :-).  I will need to do a 2nd pass analysis on my "valid_pairs" to ensure it's not cyclic. This will be good since I can imagine other failure cases.  Going to keep talking out loud here.  I will need to count the occurrences of each cut in the pair list. If all loops appear twice, it's cyclic.  If not, it's open.  However, we can imagine instances where a cut has multiple options (eg, a figure 8 torus near the cross) resulting in multiple connections from a single loop so this robustness in mesh generation will be a plus later.

**Comment by carter2422** [comment]
How would a hammerhead like object fail? In this case you wouldn't need Cyclic and so it should be ignored?

Either way, Cyclic is not a priority feature :smile:

**Comment by patmo141** [comment]
I mean it would fail w/o a manual override because to the path analysis, it would try and reconnect at the narrow point.

**Comment by carter2422** [comment]
Isn't the **Cyclic** button in the toolbar meant to be the manual override? That was my intention at least. This way if **Cyclic** is enabled, it will try and connect the strokes. If it's turned off then it will never try and connect the start/end strokes.

Am I missing something?

**Comment by patmo141** [comment]
Nope, not missing anything. It will be as you describe.  I was thinking of more failure cases with the current logic.

**Comment by carter2422** [comment]
Ah cool. Looking forward to it!

**Comment by patmo141** [comment]
This is fixed.  Occasionally it get's confused about which pair is the tip and tail, but I've crunched on it for a while and I think it's information that is not inferable (especially if the user deletes the tip stroke).  It doesn't get confused often so I'm not inclined to worry about it.
