### ISSUE TITLE
Endpoints drawn on NGons cause crash

### ISSUE THREAD

**Issue by carter2422** [CGCookie/script-bakery#8]
Anytime a guides endpoint lands on an ngon it will crash.

**Comment by patmo141** [comment]
I'm going to fix this by simply making "ngons" stop the cross section calculation but not end up with a crash.  I will add a todo/issue for proper NGon Support

**Comment by carter2422** [comment]
Sounds good!

On Sunday, May 19, 2013, patmo141 wrote:

> I'm going to fix this by simply making "ngons" stop the cross section
> calculation but not end up with a crash. I will add a todo/issue for proper
> NGon Support
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CGCookie/script-bakery/issues/8#issuecomment-18131739
> .

## 

Jonathan Williamson
http://cgcookie.com

**Comment by patmo141** [comment]
ngons are now supported with a temporary object which has all ngons triangulated.  The only reason is because the ray_cast function returns fake face indices when encountering an Ngon.  The only way to around this (because there is no predicable pattern to the fake indices) is to link a temporary object (with known indices of the triangulated faces) to the scene to have certainty of fidelity in object.ray_cast results.
