### ISSUE TITLE
Unable to undo steps?

### ISSUE THREAD

**Issue by AGorgal** [CGCookie/script-bakery#82]
I might be missing something here, but it seems like Im unable to undo a step if I mess up during the retopology process, for instance if I rotate an edge loop by mistake I cant undo it, I have to remove and draw it again. Is this intentional?

Also, this tool rocks!

**Comment by carter2422** [comment]
@linfosoma undo support for stroke is on the to-do list. But you're correct, you cannot currently do it.

A good work around for now to delete the problem stroke with **RMB** and then recreate it.

**Comment by patmo141** [comment]
The way the mesh data derived...undo would only delete the last loop so as a programmer I fail to see the difference :-)   However, I'm open to compelling arguments for why we need undo in addition to deleting.

**Comment by carter2422** [comment]
@patmo141 undo also ought to work with stroke adjustments, for undoing bad transformations. In which case delete won't work :)

**Comment by patmo141** [comment]
alright y'all....undo now works for everything pretty much.  Please try and break it because no boubt I would hate to have our undo mess up something even more.  Right now, I think it works for
1.  adding strokes
2.  Deleting strokes
3.  Transforming strokes
4.  Shifting strokes....but, it doesn't record an undo for every single shift, eg...multiple shifts on the same stroke get stacked into one undo.  So you don't have a ton of undos if you are tweaking and going back and forth.  Very proud of this :-)
5.  Alignments
6.  Segment changes.  Same behavior as 4.  Eg, if you go from 10-30 segments, it's one undo, not 20 undo steps.

<3
Patrick

**Comment by carter2422** [comment]
Fantastic @patmo141! So far I have not been able to break it and it works really well. I'll continue testing.
