### ISSUE TITLE
crash on mouseOver

### ISSUE THREAD

**Issue by RealMook** [CGCookie/script-bakery#98]
please, load this .blend: http://www.pasteall.org/blend/23470
- start Draw Contours
- make a 1st stroke (more strokes - nevermind)
- mouse over any loop
- gives the error
  http://www.pasteall.org/pic/show.php?id=57600

Previosly I got other errors while making this retopo. But this bug was started with this branch only (the 1st time).
The other errors were less critical - the contouring was finished but bridging between newly created branch wasn't due to a bug. I can report it later if necessary.

**Comment by patmo141** [comment]
It's probably been fixed since the original beta release.  I'm not having any problems with contour drawing.  However the bridging failure is happening because you are in mesh edge select mode.  I've always been in vert mode (within edit mode) when testing so never figured stumbled across that bug.  Go ahead and submit a new bug

"Bridging fails when mesh select mode is only edges"

**Comment by patmo141** [comment]
![test_bridging_bug_9](https://f.cloud.github.com/assets/2917743/978770/72140b4c-06c8-11e3-9d7a-e32bad735c7d.png)

**Comment by patmo141** [comment]
Heyo!  I was able to reproduce it actually. Doing some more testing.

**Comment by patmo141** [comment]
Ok, nailed it.

I found a lazy piece of code that uses a vector of length 1 blender unit to transform a world direction into a screen direction.  

Notice that your object is about 1 blender unit it total dimension.

For a small object, the 3d vector I create to then transform to screen space is actually out of the field of view. 

This causes the location_3d_to_region_2d to retutn "None" since...that 3d point is not visible in the 3d view.

I will solve shortly, but actually this is a matrix math tpoic that I've been meaning to figure out but working around because I thought it was non critical.  Now it's critical :-)

**Comment by RealMook** [comment]
Great! :) Klark Kent's speed!
